#!/usr/bin/bash
# mopm-name: hackgen
# mopm-url: https://github.com/yuru7/HackGen
# mopm-description: HackGen is a composite font of Hack and GenJyuu-Gothic.
# mopm-dependencies: curl, unzip, sed
# mopm-verification: find /usr/share/fonts/HackGen

TMP_FILE="/tmp/dotfiles/hackgen"
TMP_FILE_ZIP="$TMP_FILE.zip"
TMP_DIR="$(dirname "$TMP_FILE_ZIP")"

rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR"
cd "$TMP_DIR"

VERSION="$(curl -sI https://github.com/yuru7/HackGen/releases/latest | grep location | awk -F '/' '{print $NF }')"
# 改行削除
VERSION=`echo "$VERSION" | sed -e 's/\n//g' | sed -e 's/\r//g' | sed -e 's/ //g'`
URL="https://github.com/yuru7/HackGen/releases/download/$VERSION/HackGen_$VERSION.zip"

echo "Download HackGen font from $URL"
curl -fsSL "$URL" -o "$TMP_FILE_ZIP"
unzip "$TMP_FILE"
mv "HackGen_$VERSION" "/usr/share/fonts/HackGen"
fc-cache -fv
