#!/usr/bin/bash
# mopm-url: https://github.com/basd4g/mopm-bash
# mopm-description: A installation testing package for mopm-bash
# mopm-dependencies: e, f
# mopm-verification: find /tmp/mopm-defs-test/b-is-installed
mkdir -p /tmp/mopm-defs-test
touch /tmp/mopm-defs-test/b-is-installed
