#!/usr/bin/bash
# mopm-url: https://rust-lang.org
# mopm-description: Rust language
# mopm-dependencies: curl
# mopm-verification: which cargo
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
